config/routes.rb
Rails.application.routes.draw do
  get 'preguntas_frecuentes/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :redessociales
  resources :academia, only: [:index]
  resources :preguntasfrecuentes, only: [:index]
  get 'preguntas_frecuentes', to: 'preguntas_frecuentes#index'

  # post "academia/maquillaje", to: "academia#maquillaje"
  get '/academia/maquillaje', to: 'academia#maquillaje', as: 'academia_maquillaje'
  get '/academia/maquillaje/automaquillaje', to: 'academia#automaquillaje', as: 'academia_maquillaje_automaquillaje'
  get '/academia/maquillaje/skincare', to: 'academia#skincare', as: 'academia_maquillaje_skincare'
  get '/academia/maquillaje/teoriadelcolor', to: 'academia#teoriadelcolor', as: 'academia_maquillaje_teoriadelcolor'




  get '/academia/peinado', to: 'academia#peinado', as: 'academia_peinado'
  get '/academia/peinado/peinadoprofesional', to: 'academia#peinadoprofesional', as: 'academia_peinado_peinadoprofesional'

  get '/academia/peinado/peinadoparamaquilladores', to: 'academia#peinadoparamaquilladores', as: 'academia_peinado_peinadoparamaquilladores'
  get '/academia/peinado/peinadoparaplaya', to: 'academia#peinadoparaplaya', as: 'academia_peinado_peinadoparaplaya'
  get '/academia/peinado/extensiones1', to: 'academia#extensiones1', as: 'academia_peinado_extensiones1'
  get '/academia/peinado/extensiones2', to: 'academia#extensiones2', as: 'academia_peinado_extensiones2'

  get '/academia/unas', to: 'academia#unas', as: 'academia_unas'
  get '/academia/unas/cartoon', to: 'academia#cartoon', as: 'academia_unas_cartoon'
  get '/academia/unas/drymanicura', to: 'academia#drymanicura', as: 'academia_unas_drymanicura'
  get '/academia/unas/dualsystemacrilico', to: 'academia#dualsystemacrilico', as: 'academia_unas_dualsystemacrilico'
  get '/academia/unas/dualsystempolygel', to: 'academia#dualsystempolygel', as: 'academia_unas_dualsystempolygel'
  get '/academia/unas/hiperrealismo', to: 'academia#hiperrealismo', as: 'academia_unas_hiperrealismo'
  get '/academia/unas/manicuraspa', to: 'academia#manicuraspa', as: 'academia_unas_manicuraspa'
  get '/academia/unas/polygel1', to: 'academia#polygel1', as: 'academia_unas_polygel1'
  get '/academia/unas/polygel2', to: 'academia#polygel2', as: 'academia_unas_polygel2'
  get '/academia/unas/polygel3', to: 'academia#polygel3', as: 'academia_unas_polygel3'
  get '/academia/unas/presson', to: 'academia#presson', as: 'academia_unas_presson'
  get '/academia/unas/semipermanente', to: 'academia#semipermanente', as: 'academia_unas_semipermanente'
  get '/academia/unas/softgel', to: 'academia#softgel', as: 'academia_unas_softgel'
  get '/academia/unas/tecnicamixta', to: 'academia#tecnicamixta', as: 'academia_unas_tecnicamixta'
  get '/academia/unas/unas3d', to: 'academia#unas3d', as: 'academia_unas_unas3d'
  get '/academia/unas/unasacrilica1', to: 'academia#unasacrilica1', as: 'academia_unas_unasacrilica1'
  get '/academia/unas/unasacrilica2', to: 'academia#unasacrilica2', as: 'academia_unas_unasacrilica2'
  get '/academia/unas/unasacrilica3', to: 'academia#unasacrilica3', as: 'academia_unas_unasacrilica3'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/academia_controller.rb
class AcademiaController < ApplicationController

  skip_before_action :authenticate_user!

  def index

  end

  def maquillaje
    # Lógica para la ruta /academia/maquillaje
  end


  def automaquillaje
  end

  def skincare

  end

  def teoriadelcolor

  end

  def peinado

  end

  def peinadoprofesional

  end

  def peinadoparamaquilladores

  end

  def peinadoparaplaya

  end

  def extensiones1

  end

  def extensiones2

  end

  def unas

  end

  def cartoon

  end

  def drymanicura

  end

  def dualsystemacrilico

  end

  def dualsystempolygel

  end
  def hiperrealismo

  end
  def manicuraspa

  end

  def polygel1

  end

  def polygel2

  end

  def polygel3

  end

  def presson

  end

  def semipermanente

  end

  def tecnicamixta

  end
  def softgel

  end

  def unas3d

  end

  def unasacrilica1

  end

  def unasacrilica2

  end

  def unasacrilica3

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/preguntas_frecuentes_controller.rb
class PreguntasFrecuentesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/redessociales_controller.rb
class RedessocialesController < ApplicationController
  skip_before_action :authenticate_user!
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/academia/automaquillaje.html.erb
<% @titulo_del_curso = "AutoMaquillaje" %>
<% @videoyoutube = "https://www.youtube.com/embed/3inw26U-os4" %>
<% @horas_de_curso ="" %>
<% @contcurso = "
<ul>
<li>
  <strong>Organización del área de trabajo.</strong>
</li>
<li>
  <strong>Fundamentos del maquillaje.</strong>
</li>
<li>
  <strong>Etapa de preparación.</strong>
  <ul>
    <li><i>Cuidado del cutis.</i></li>
    <li><i>Correcciones del cutis.</i></li>
  </ul>
</li>
<li>
  <strong>Base de maquillaje.</strong>
  <ul>
    <li><i>Teoría del color: la piel.</i>
      <ul>
        <li><i>Tonos y subtonos</i></li>

      </ul>
    </li>

    <li><i>Morfología y visagismo.</i>
      <ul>
        <li><i>Técnica del claro-obscuro.</i></li>

      </ul>
    </li>
    <li><i>Base tradicional.</i></li>
    <li><i>Base con correcciones por arriba.</i></li>
    <li><i>Base con correcciones por abajo.</i></li>
  </ul>
</li>
<li>
  <strong>Cejas.</strong>
  <ul>
    <li><i>Teoría del color: el pelo.</i></li>
    <li><i>Mapeo de cejas.</i></li>
    <li><i>Diseño de cejas.</i></li>
  </ul>
</li>
<li>
  <strong>Ojos.</strong>
  <ul>
    <li><i>Teoría del color: los párpados y ojeras.</i></li>
    <li><i>Preparación del contorno de ojos.</i></li>
    <li><i>Resolución de casos en ojos.</i>
      <ul>
        <li><i>Técnicas de sombreado en ojos.</i></li>
        <li><i>Delineados.</i></li>
        <li><i>Pestañas.</i></li>

      </ul>

    </li>
  </ul>
</li>
<li>
  <strong>Labios.</strong>
  <ul>
    <li><i>Teoría del color: los labios.</i></li>
    <li><i>Mapeo de labios.</i></li>
    <li><i>Diseño de labios.</i></li>
  </ul>
</li>
<li>
  <strong>Acabado de maquillaje.</strong>
  <ul>
    <li><i>Bronceador.</i></li>
    <li><i>Rubor.</i></li>
    <li><i>Iluminador.</i></li>
    <li><i>Fijador de maquillaje.</i></li>
  </ul>
</li>
<li>
  <strong>Después del maquillaje.</strong>
</li>
</ul>
Técnicas de maquillaje que aprenderás: teoría básica del color para maquillar, pasos de una rutina de skincare, tres tipos de aplicación de bases de maquillaje, dos diseños de cejas, seis técnicas de sombreado en ojos, dos tipos de delineados, dos tipos de clasificación de pestañas, 4 técnicas de aplicación de pestañas, cuatro diseños de labios, larga duración en tu maquillaje para todo tipo de piel y climas.
" %>


<% @imagen="automaquillaje.png" %>










<%= render 'shared/informacioncursos' %>

app/views/academia/cartoon.html.erb
<% @titulo_del_curso = "Página de cartoon" %>
<% @videoyoutube = "https://www.youtube.com/embed/3inw26U-os4" %>
<% @nivel= "Nivel: Intermedio" %>
<% @contcurso= "" %>
<% @ventajas= %>











<%= render 'shared/informacioncursos' %>

app/views/academia/drymanicura.html.erb
<% @titulo_pagina = "Página de drymanicura" %>
<%= render 'shared/informacioncursos' %>

app/views/academia/maquillaje.html.erb
    <% @logo_image="1.png" %>
<div class="d-flex justify-content-evenly mt-5">
  <div class="card cardcursos border-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header text-center">Curso de Automaquillaje Profesional</div>
    <div class="card-body text-secondary">
    <%= link_to academia_maquillaje_automaquillaje_path do %>

      <%= image_tag "automaquillaje.png", class: "card-img-top", alt: "maquillaje" %>
      <% end %>


    <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
    <div class="d-grid gap-2">
      <%= link_to "Más Información...", academia_maquillaje_automaquillaje_path, class: "btn btn-primary botonsuscribete" %>
    </div>

  <br>
    <p>Aprenderás a maquillarte desde cero.</p>
    </div>
  </div>

    <div class="card cardcursos border-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header text-center">Curso Rutina de Skin Care.</div>
    <div class="card-body text-secondary">
    <%= link_to academia_maquillaje_skincare_path do %>
      <%= image_tag "skincare.png", class: "card-img-top", alt: "maquillaje" %>
      <%end  %>

    <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
    <div class="d-grid gap-2">
      <%= link_to "Más Información...", academia_maquillaje_skincare_path, class: "btn btn-primary botonsuscribete" %>

    </div>

  <br>
    <p>Aprenderás a realizarte una rutina de skin care correcta de principio a fin.</p>
    </div>
  </div>





    <div class="card cardcursos border-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header text-center">Teoría de Color Para Maquillaje.</div>
    <div class="card-body text-secondary">
    <%= link_to academia_maquillaje_teoriadelcolor_path do %>
      <%= image_tag "tdelcolor.png", class: "card-img-top", alt: "maquillaje" %>
      <% end %>


    <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
    <div class="d-grid gap-2">
      <%= link_to "Más Información...", academia_maquillaje_teoriadelcolor_path, class: "btn btn-primary botonsuscribete" %>
    </div>

  <br>
    <p>Aprenderás a hacer todas las combinaciones posibles entre colores del circulo cromático para usarlos
     en sombras para ojos, labiales, etc., y a darle armonía de color a tu maquillaje.</p>
    </div>
  </div>


</div>


  <%# <style>
    .dropdown-content {
      display: none;
    }
    .dropdown-content.show {
      display: block;
    }
  </style>

  <div class="dropdown">
    <a href="#" class="dropdown-toggl" onclick="toggleDropdown()">Ver Contenido &#9660;</a>
    <div id="dropdownContent" class="dropdown-content">
      <!-- Contenido adicional -->
      <p>Contenido:</p>
      <ul>
        <li><strong>Fundamentos del maquillaje.</strong></li>
        <li><strong>Organización del área del trabajo.</strong> </li>
        <li><strong>Etapa de preparación.</strong>
          <ul>
            <li><em> Cuidado del cutis.</em></li>
            <li><em>Correcciones del cutis.</em></li>
          </ul>
        </li>
        <li><strong>Base de maquillaje.</strong>
          <ul>
            <li><em>Teoría del color: la piel.</em>
              <ul>
                <li>Tonos y subtonos.</li>
              </ul>
            </li>
            <li><em>Morfología y visagismo.</em>
              <ul>
                <li>Técnica del claro-obscuro.</li>
              </ul>
            </li>
            <li><em>Base tradicional.</em></li>
            <li><em>Base con correcciones por arriba.</em></li>
            <li><em>Base con correcciones por abajo.</em></li>
          </ul>

        </li>
        <li><strong>Cejas.</strong>
          <ul>
            <li><em>Teoría del color: el pelo.</em></li>
            <li><em>Mapeo de cejas.</em></li>
            <li><em>Diseño de cejas.</em></li>
          </ul>
        </li>
        <li><strong>Ojos.</strong>
          <ul>
            <li><em>Teoría del color: los parpados y ojeras.</em></li>
            <li><em>Preparación del contorno de ojos.</em></li>
            <li><em>Resolución de casos en ojos.</em>
              <ul>
                <li>Técnicas de sombreado en ojos.</li>
                <li>Delineados.</li>
                <li>Pestañas.</li>
              </ul>
            </li>
          </ul>
        </li>
        <li><strong>Labios.</strong>
          <ul>
            <li><em>Teoría del color: los labios.</em></li>
            <li><em>Mapeo de labios.</em></li>
            <li><em>Diseño de labios.</em></li>
          </ul>
        </li>
        <li><strong>Acabado de maquillaje.</strong>
          <ul>
            <li><em>Bronceador.</em></li>
            <li><em>Rubor.</em></li>
            <li><em>Iluminador.</em></li>
            <li><em>Fijador de maquillaje.</em></li>

          </ul>
        </li>
        <li><strong>Después del maquillaje.</strong></li>
      </ul>

    </div>
  </div>

  <script>
    function toggleDropdown() {
      var dropdownContent = document.getElementById("dropdownContent");
      dropdownContent.classList.toggle("show");

      var dropdownToggle = document.querySelector(".dropdown-toggl  ");
      if (dropdownContent.classList.contains("show")) {
        dropdownToggle.innerHTML = "Ver menos &#9650;";
      } else {
        dropdownToggle.innerHTML = "Ver Contenido &#9660;";
      }
    }
  </script>



      <p style=" text-align: justify;">Técnicas de maquillaje que aprenderás: teoría básica del color para maquillar,
      pasos de una rutina de skincare, tres tipos de aplicación de bases de maquillaje, dos diseños de cejas,
      seis técnicas de sombreado en ojos, dos tipos de delineados, dos tipos de clasificación de pestañas,
        4 técnicas de aplicación de pestañas, cuatro diseños de labios, larga duración en tu maquillaje para
        todo tipo de piel y climas.</p> %>

app/views/academia/peinado.html.erb
<div class="container">
  <div class="row">
  <div class="d-flex justify-content-evenly mt-5">

    <div class="card cardcursos border-secondary mb-3 col" style="max-width: 18rem;">
      <div class="card-header text-center">Curso de Peinado Profesional</div>
      <div class="card-body text-secondary">
      <%= link_to academia_peinado_peinadoprofesional_path do %>
        <%= image_tag "peinadoprofesional.png", class: "card-img-top", alt: "maquillaje" %>
        <% end %>


      <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
      <div class="d-grid gap-2">
        <%= link_to "Más Información...", academia_peinado_peinadoprofesional_path, class: "btn btn-primary botonsuscribete" %>
      </div>

    <br>
      <p>Aprenderás a peinar desde cero.</p>
      </div>
    </div>



    <div class="card cardcursos border-secondary mb-3 col" style="max-width: 18rem;">
      <div class="card-header text-center">Curso de Peinado Para Maquilladores.</div>
      <div class="card-body text-secondary">
      <%= link_to academia_peinado_peinadoparamaquilladores_path do %>

        <%= image_tag "peinadomaquilladores.png", class: "card-img-top", alt: "maquillaje" %>
        <% end %>


      <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
      <div class="d-grid gap-2">
        <%= link_to "Más Información...", academia_peinado_peinadoparamaquilladores_path, class: "btn btn-primary botonsuscribete" %>
      </div>

    <br>
      <p>Ofrece un servicio de belleza integral ampliando tu catálogo de servicios de maquillaje con el servicio de diseño personalizado
      de peinado profesional de acuerdo a las necesidades de tu cliente.</p>
      </div>
    </div>



      <div class="card cardcursos border-secondary mb-3 col" style="max-width: 18rem;">
      <div class="card-header text-center">Curso de Peinados para Playa.</div>
      <div class="card-body text-secondary">
      <%= link_to academia_peinado_peinadoparaplaya_path do %>
        <%= image_tag "peinadoplaya.png", class: "card-img-top", alt: "maquillaje" %>
        <%end  %>

      <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
      <div class="d-grid gap-2">
        <%= link_to "Más Información...", academia_peinado_peinadoparaplaya_path, class: "btn btn-primary botonsuscribete" %>

      </div>

    <br>
      <p>Aprenderás a preparar de forma correcta el cabello de tus clientes para lograr peinados duraderos garantizando su duración
      en un evento de playa o en climas húmedos.</p>
      </div>
    </div>





      <div class="card cardcursos border-secondary mb-3 col" style="max-width: 18rem;">
      <div class="card-header text-center">Curso de Extensiones de Cabello 1.</div>
      <div class="card-body text-secondary">
      <%= link_to academia_peinado_extensiones1_path do %>
        <%= image_tag "extensiones1.png", class: "card-img-top", alt: "maquillaje" %>
        <% end %>


      <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
      <div class="d-grid gap-2">
        <%= link_to "Más Información...", academia_peinado_extensiones1_path, class: "btn btn-primary botonsuscribete" %>
      </div>

    <br>
      <p>Aprende cinco técnicas de aplicación, cuidado de extensiones, retiro y efecto glitter de manera profesional.</p>
      </div>
    </div>
  </div>
  <div class="row">
  <div class="d-flex justify-content-evenly mt-5">
        <div class="card cardcursos border-secondary mb-3 col" style="max-width: 18rem;">
        <div class="card-header text-center">Curso de Extensiones de Cabello 2</div>
        <div class="card-body text-secondary">
      <%= link_to academia_peinado_extensiones2_path do %>
        <%= image_tag "extensiones2.png", class: "card-img-top", alt: "maquillaje" %>
        <% end %>


        <h5 class="text-center mt-2"><strong>550 MXN / mes</strong></h5>
        <div class="d-grid gap-2">
        <%= link_to "Más Información...", academia_peinado_extensiones2_path, class: "btn btn-primary botonsuscribete" %>
        </div>

        <br>
        <p>Aprende dos técnicas de aplicación, cuidado de extensiones, retiro y la técnica de combinación manual para lograr efectos de color como todo un profesional.</p>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Viridiana Raya Beauty</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'vrbeauty.png' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round&display=swap" rel="stylesheet">
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> %>
<%# <meta name="viewport" content="width=device-width, initial-scale=1"> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag  "application", "data-turbo-track": "reload",  defer: true %>
  </head>

  </head>
  <header>


    <%= render "shared/navbar" %>

  </header>

  <body>
    <div class="contenedor">
      <%= yield %>
      <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> %>
    </div>

  </body>

  <footer>
    <%= render "shared/footer" %>
  </footer>
</html>

app/views/pages/home.html.erb
<style>
  .inicio a{
  color:#FF0099;
}
</style>



<div class="mt-3">
  <div class=container>
    <div class="container ">
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
             <%= link_to academia_path do %>
              <%= image_tag "foto1.png", class: "d-block w-100", alt: "second slide" %>
            <% end %>
          </div>






          <div class="carousel-item">
            <%= image_tag "foto2.png", class: "d-block w-100", alt: "second slide" %>
          </div>
         <div class="carousel-item">
  <%= link_to "#seccion2", data: { target: "#seccion2" } do %>
    <%= image_tag "foto3.png", class: "d-block w-100", alt: "third slide" %>
  <% end %>
</div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
  </div>


  <div class="container" id="seccion2">

    <div class="container mt-4 mb-1">
      <div class="row">
        <div class="col-12 col-md-5 imagenpresentacion" style="background-image: url('<%= asset_path('biografia.png') %>')">



        <button class="accordion" >VIRIDIANA RAYA</button>
        <div class="panel">

          <a href="https://www.youtube.com/channel/UCsR5VIZwGN9pzyBp3OqvTQw" target="_blank"><%= image_tag "youtube.png", :size =>"18x18"  %></a>
          <a href="https://www.facebook.com/ViridianaRayaOficial" target="_blank"><%= image_tag "facebook.png", :size =>"18x18", class:"ms-2"%></a>
          <a href="https://www.instagram.com/viridiana.raya/?fbclid=IwAR2xywRAXBPLDnGZ2zX1Mhu3e-E5oH9KNBLEqeXQHMqEFuZMPeI_OPsfYJE" target="_blank"><%= image_tag "instagram.png", :size =>"18x18", class:"ms-2"  %></a>
          <a href="https://www.tiktok.com/@viridiana.raya?fbclid=IwAR3mHTnW1TkA5fkEooIYDgh4oWvu8wDlnv_wxw47PzaGrsDwUqEZs6qmoCg" target="_blank"><%= image_tag "tik-tok(3).png", :size =>"18x18", class:"ms-2"  %></a>
          <a href="#" target="_blank"><%= image_tag "twitter.png", :size =>"18x18", class:"ms-2"  %></a>
        </div>



      </div>
      <div class="col-12 col-md-7" >
        <div class="row mt-1">
          <div class="col d-flex justify-content-center card-presentation align-items-center">
            <p style=" text-align: justify;" >Diseñadora Profesional de Maquillaje, Peinado y Uñas
            certificada ante la SEP-CONOCER México; con más de tres años de experiencia en la
            industria de la belleza. Cuento con la certificación internacional “Temptu Pro’s Basic
            and Advanced Airbrush Cosmetics Training” de la marca Temptu Cosmetics de Nueva York,
            Estados Unidos, documento que me acredita como especialista en técnicas de maquillaje
            aerográfico. Así como también cuento con la acreditación de Técnica Aplicadora de la marca
            Organic Nails.</p>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="container mb-2">
    <div class="row  d-flex justify-content-center">
      <div class="col-4 ms-lg-4 mt-3 card-jobs text-center d-flex align-items-center justify-content-center">

        <div class="mt-3">
          <h3>MISIÓN</h3>
          <p >
          Compartir con la comunidad digital conocimientos sobre la industria de la belleza que no
          son de fácil acceso para que los aprovechen en sus labores diarias como prestadores de
          servicios en esta industria.</p>
         </div>
      </div>
      <div class="col-4 ms-md-4 mt-3 card-jobs text-center d-flex align-items-center justify-content-center">
          <div>
          <h3>VISIÓN</h3>
          <p >
          Convertirnos en un referente digital de habla hispana que le permita a cualquier persona con dispositivo
          conectado a internet aprender las habilidades profesionales que aquí se exponen.</p>
         </div>
      </div>
            <div class="col-4 ms-md-4 mt-3 card-jobs text-center d-flex align-items-center justify-content-center">
          <div>
          <h3>VALORES</h3>

          <div>Pasión.</div>
          <div>Compromiso.</div>
          <div>Creatividad.</div>

          <div>Resiliencia.</div>
          <div>Gratitud.</div>


         </div>
      </div>


    </div>
  </div>
</div>

app/views/preguntas_frecuentes/index.html.erb
<style>
  .preguntafrecuente a{
    color:#FF0099;
}
</style>
    <% @logo_image="4.png" %>

app/views/shared/_navbar.html.erb
<div class="colornav pb-5">
  <div class="container colornav">
    <nav class="pd-3">
  <% logo_image = "2.png"%>

<div class="logo">
  <%= image_tag @logo_image || "2.png", size: "190x110" %>
</div>
    </nav>
    <div class="row justify-content-evenly">
      <div class="navv col-2 inicio"><%= link_to "Inicio", root_path %></div>
      <div class="navv col-2 academia"><%= link_to "Academia", academia_path %></div>
      <div class="navv col-2"><a href="#">Productos</a></div>
      <div class="navv col-2 redessociales"><%= link_to "Redes Sociales", redessociales_path %></div>

      <div class="navv col-2"><a href="#">Contacto</a></div>
      <div class="navv col-2 preguntafrecuente"><%= link_to "Preguntas Frecuentes", preguntas_frecuentes_index_path %></div>
    </div>

  </div>
</div>